import Anthropic from "@anthropic-ai/sdk";
import type { SubmissionProfile } from "./types";

/**
 * Smart fallback for required text/textarea fields the form-filler doesn't
 * have a profile mapping for. Replaces the dumb "N/A" sentinel with a
 * concrete, tailored answer generated by a single batched Claude call.
 *
 * Why batched: each /submit run lives inside a 60s Vercel budget, and the
 * fill step happens after the page is open and other LLM work is already
 * done. One round-trip with all unknown fields keeps us under budget; per
 * field calls do not.
 */

export type UnknownField = {
  selector: string; // e.g. "#question_12345"
  label: string; // visible label text
  helperText?: string; // any text near the field that explains it
  kind: "text" | "textarea";
  maxLength?: number; // honor this if set on the input
};

export type SmartFillContext = {
  profile: SubmissionProfile;
  job: { company: string; title: string; jdSummary: string };
};

/** Hard server-side guard so a chatty model can't blow past field limits. */
const TEXT_INPUT_HARD_CAP = 120;
const TEXTAREA_DEFAULT_CAP = 600;

/** Anthropic call timeout — total fill budget is tight. */
const ANTHROPIC_TIMEOUT_MS = 12_000;

const SYSTEM_PROMPT = `You are filling in unknown miscellaneous fields on a job application on behalf of a real candidate. The form-filler has a profile mapping for the common fields (name, email, work auth, demographics, etc.) but a handful of free-text fields didn't match any known pattern — you're the fallback so the form actually submits with a real, tailored answer instead of "N/A".

Rules:
- Write in the candidate's voice, first person, plain prose. No bullet points, no markdown, no headers.
- Be CONCRETE and SPECIFIC. Pull real details from the candidate profile and the job context (company name, role, JD). Reference actual experience, companies, technologies, or interests that appear in the profile.
- No filler openers like "I am excited to apply" or "Thank you for considering me." Get straight to the substance.
- If a field has a maxLength, the answer MUST fit within it (count characters, not tokens). When in doubt, undershoot.
- For short text inputs (kind="text"), one short phrase or a single sentence is usually right — these are things like "Salary expectation", "Earliest start date", "Years of experience", "Referral source".
- For textarea fields (kind="textarea"), 2-3 sentences max. These are things like "Why this company?", "Why this role?", "Tell us about a project."
- If you genuinely cannot infer a sensible answer from the profile + job context (e.g. an obscure trivia question), respond with a brief honest answer like "Open to discussion" or "Available to discuss" — never invent facts about the candidate.
- Numeric/date-style questions ("desired salary", "notice period", "start date"): give a plausible, conservative answer. For salary: "Open to discussion based on the full package" or similar. For start date: "Two weeks' notice from offer acceptance" if no current job info, otherwise infer from currentJobTitle presence.

Output: a single JSON object mapping each field's selector to its answer string. No commentary, no other keys.`;

/** Filter the profile down to the fields safe + useful to send into the prompt. */
function slimProfile(profile: SubmissionProfile): Record<string, unknown> {
  return {
    fullName: profile.fullName,
    location: profile.location,
    currentCompany: profile.currentCompany,
    currentJobTitle: profile.currentJobTitle,
    linkedinUrl: profile.linkedinUrl,
    portfolioUrl: profile.portfolioUrl,
    githubUrl: profile.githubUrl,
    workAuthorization: profile.workAuthorization,
    needsSponsorship: profile.needsSponsorship,
    currentlyAuthorizedUS: profile.currentlyAuthorizedUS,
    countryOfResidence: profile.countryOfResidence,
    countryOfWork: profile.countryOfWork,
    eeoGender: profile.eeoGender,
    skillYears: profile.skillYears,
  };
}

function buildUserPrompt(fields: UnknownField[], ctx: SmartFillContext): string {
  const slim = slimProfile(ctx.profile);
  const fieldsBlock = fields
    .map((f, i) => {
      const parts = [`${i + 1}. selector: ${f.selector}`, `   kind: ${f.kind}`, `   label: ${f.label}`];
      if (f.helperText) parts.push(`   helperText: ${f.helperText}`);
      if (typeof f.maxLength === "number") parts.push(`   maxLength: ${f.maxLength}`);
      return parts.join("\n");
    })
    .join("\n\n");

  const jdSummary = ctx.job.jdSummary.trim().length > 0 ? ctx.job.jdSummary : "(no JD summary available — work from company + title)";

  return [
    "JOB CONTEXT",
    `Company: ${ctx.job.company}`,
    `Title: ${ctx.job.title}`,
    `JD summary: ${jdSummary}`,
    "",
    "CANDIDATE PROFILE (JSON)",
    JSON.stringify(slim, null, 2),
    "",
    "FIELDS TO ANSWER",
    fieldsBlock,
    "",
    "Respond with a single JSON object where each key is the exact selector string above and each value is the answer string. Example: {\"#question_1\": \"...\", \"#question_2\": \"...\"}. Do not include any other keys or commentary.",
  ].join("\n");
}

/** Clip an answer to the right cap for its field kind / explicit maxLength. */
function clipAnswer(answer: string, field: UnknownField): string {
  const trimmed = answer.trim();
  const cap =
    typeof field.maxLength === "number"
      ? field.maxLength
      : field.kind === "textarea"
        ? TEXTAREA_DEFAULT_CAP
        : TEXT_INPUT_HARD_CAP;
  if (trimmed.length <= cap) return trimmed;
  // Hard truncate, but try to cut at a sentence boundary if there's one in
  // the last ~20% of the capped window so we don't end mid-word.
  const slice = trimmed.slice(0, cap);
  const lastSentence = slice.lastIndexOf(".");
  if (lastSentence > cap * 0.6) return slice.slice(0, lastSentence + 1);
  return slice;
}

/**
 * Batch-infer answers for unknown form fields using one Claude call.
 *
 * Returns a Map keyed by selector so the caller can match answers back to
 * the exact input. On any failure (no API key, timeout, bad JSON, etc.)
 * returns an empty map — caller is expected to fall back to "N/A".
 */
export async function inferAnswers(
  fields: UnknownField[],
  ctx: SmartFillContext,
): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  if (fields.length === 0) return out;
  if (!process.env.ANTHROPIC_API_KEY) return out;

  const client = new Anthropic();
  const userPrompt = buildUserPrompt(fields, ctx);

  // Wrap the SDK call in our own timeout — the SDK's internal retries can
  // otherwise eat through our budget while we wait.
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ANTHROPIC_TIMEOUT_MS);

  try {
    const tryModels: string[] = ["claude-haiku-4-5", "claude-sonnet-4-6"];
    let parsed: Record<string, string> | null = null;

    for (const model of tryModels) {
      try {
        const response = await client.messages.create(
          {
            model,
            max_tokens: 1500,
            system: SYSTEM_PROMPT,
            messages: [{ role: "user", content: userPrompt }],
          },
          { signal: controller.signal },
        );
        const textBlock = response.content.find((b) => b.type === "text");
        if (!textBlock || textBlock.type !== "text") continue;
        const raw = textBlock.text.trim();
        // Tolerate accidental code-fence wrapping.
        const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "").trim();
        try {
          parsed = JSON.parse(cleaned) as Record<string, string>;
          break;
        } catch {
          // try next model
        }
      } catch {
        // try next model, unless the abort fired
        if (controller.signal.aborted) break;
      }
    }

    if (!parsed) return out;

    for (const f of fields) {
      const raw = parsed[f.selector];
      if (typeof raw !== "string" || raw.trim().length === 0) continue;
      out.set(f.selector, clipAnswer(raw, f));
    }
    return out;
  } catch {
    return out;
  } finally {
    clearTimeout(timer);
  }
}
