export type SubmissionProfile = {
  fullName: string;
  firstName: string;
  lastName: string;
  preferredName: string | null;
  email: string;
  phone: string | null;
  location: string | null;
  linkedinUrl: string | null;
  githubUrl: string | null;
  portfolioUrl: string | null;
  workAuthorization: string | null;
  needsSponsorship: boolean;
  countryOfResidence: string | null;
  countryOfWork: string | null;
  employmentRestrictions: boolean;
  previouslyWorkedHere: boolean;
  accommodationsNeeded: string | null;
  eeoGender: string;
  eeoHispanicLatino: string;
  eeoRaceEthnicity: string;
  eeoVeteranStatus: string;
  eeoDisabilityStatus: string;
  eeoSexualOrientation: string;
  currentCompany: string | null;
  currentJobTitle: string | null;
  currentlyAuthorizedUS: boolean;
  skillYears: Record<string, number | null>;
  voiceSample: string | null;
  resumePdfBytes: Buffer | null;
  resumeFileName: string;
  coverLetter: string;
  screeners: Array<{ question: string; answer: string; confidence: string }>;
};

export type SubmissionStep = {
  step: string;
  detail: string;
  ok: boolean;
};

/**
 * Per-field resolution record. Persisted on application.customAnswersJson
 * so the Phase D review UI can render each filled field with its source
 * and confidence, and so we can audit why a low-confidence form was
 * routed to a human.
 *
 * Phase 1 populates the entries Phase 2's resolveFieldValue() will later
 * return directly. Source values:
 *   - "profile":       directly from a profile field (name, email, …)
 *   - "deterministic": matched by the profileMap regex catalog
 *   - "hardcoded":     a fixed answer we admit is a guess ("LinkedIn")
 *   - "exact":         option list contained an exact answer match
 *   - "polarity":      yes/no polarity match in a React-Select
 *   - "fuzzy":         fuzzy keyword-overlap fallback
 *   - "llm":           smart-fill generated by Claude
 *   - "abstain":       no confident answer — left blank
 *
 * Confidence:
 *   - "high":    profile/exact/deterministic — typed verbatim from profile
 *                or chosen by a known-good mapping
 *   - "medium":  llm/hardcoded/polarity/fuzzy — plausible but not verified
 *   - "low":     a guess the resolver itself flagged as risky
 *   - "abstain": no value
 */
export type ResolvedField = {
  label: string;
  value: string | null;
  source:
    | "profile"
    | "deterministic"
    | "hardcoded"
    | "exact"
    | "polarity"
    | "fuzzy"
    | "llm"
    | "abstain";
  confidence: "high" | "medium" | "low" | "abstain";
  reason: string;
};

export type SubmissionResult = {
  ok: boolean;
  ats: "greenhouse" | "lever" | "ashby" | "unknown";
  steps: SubmissionStep[];
  resolvedFields: ResolvedField[];
  finalUrl: string;
  liveViewUrl: string;
  realSubmitted: boolean;
  error: string | null;
};
